### ISSUE TITLE
Consider leaving Sourceforge

### ISSUE THREAD

**Issue by antaflos** [grgrzybek/tomcat-slf4j-logback#66]
Given the recent issues surrounding Sourceforge and their behaviour towards hosted projects, like bundling adware/crapware/malware with installers, hijacking accounts of inactive projects, etc, you might want to consider hosting your downloads somewhere else. Blockers like uBlock Origin have already blacklisted Sourceforge because of this.

Notepad++ has summarised the situation succinctly: https://notepad-plus-plus.org/news/notepad-plus-plus-leaves-sf.html

Here is a page that also summarises what happened and which alternatives to Sourceforge are available: http://helb.github.io/goodbye-sourceforge/

It is probably easiest to host the binary downloads directly on Github.

**Comment by hazendaz** [comment]
I guess we could change.  I really don't see a need to be out on sourceforge anyways.  This project did use the downloads section back in 2012 but hasn't since.  If there is a way to direct traffic over here from source forge that would cement the deal of getting off sourceforge.  Given this project has no installer to start with and the level of downloads that happen on sourceforge, I wouldn't want to rush to jump just because a few have ran into issues.  We are prepared to start releasing to maven central as well but haven't done so yet as it's at this point unclear how we will mark tomcat-juli for distribution.  See other issue on that #58

**Comment by hazendaz** [comment]
I'm closing this issue.  All new releases will be made available on github.  All prior releases will remain with sourceforge.
